import localFont from 'next/font/local';
import Header from "@/components/Header/Header";
// import Footer from "@/components/Footer/Footer";
import FooterCurrent from "@/components/FooterCurrent/FooterCurrent";
import "./globals.scss";


const satoshiRegular = localFont({
  src: '../fonts/Satoshi-Regular.woff2',
  weight: '400',
  variable: '--regular',
});

export const metadata = {
  title: "OTHON Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={satoshiRegular.variable}>
      <body
        style={{ overflowX: "hidden", overflowY: "auto" }}
      >
        <Header />
        <main>
          {children}
        </main>
        {/* <Footer /> */}
        <FooterCurrent />
      </body>
    </html>
  );
}
